/** Development fixture catalogue. Not imported by the HTTP server. */

export const seedCategories = [
  {
    name: 'Fashion',
    slug: 'fashion',
    description: 'Everyday essentials and occasion wear, chosen for fabric and fit.',
    image: { url: '', alt: 'Fashion category' },
    displayOrder: 1,
  },
  {
    name: 'Home & Kitchen',
    slug: 'home-kitchen',
    description: 'Cookware, storage and decor that earn their place on the shelf.',
    image: { url: '', alt: 'Home and kitchen category' },
    displayOrder: 2,
  },
  {
    name: 'Jewellery',
    slug: 'jewellery',
    description: 'Understated pieces in silver, brass and semi-precious stone.',
    image: { url: '', alt: 'Jewellery category' },
    displayOrder: 3,
  },
  {
    name: 'Beauty',
    slug: 'beauty',
    description: 'Skincare and grooming with short, readable ingredient lists.',
    image: { url: '', alt: 'Beauty category' },
    displayOrder: 4,
  },
  {
    name: 'Toys',
    slug: 'toys',
    description: 'Open-ended toys and games built to survive real children.',
    image: { url: '', alt: 'Toys category' },
    displayOrder: 5,
  },
  {
    name: 'Bags',
    slug: 'bags',
    description: 'Totes, backpacks and travel bags with hardware that lasts.',
    image: { url: '', alt: 'Bags category' },
    displayOrder: 6,
  },
  {
    name: 'Stationery',
    slug: 'stationery',
    description: 'Notebooks, pens and desk tools for people who still write.',
    image: { url: '', alt: 'Stationery category' },
    displayOrder: 7,
  },
  {
    name: 'Gifts',
    slug: 'gifts',
    description: 'Ready-to-give sets for birthdays, weddings and festivals.',
    image: { url: '', alt: 'Gifts category' },
    displayOrder: 8,
  },
];

function daysAgo(days) {
  return new Date(Date.now() - days * 86400000);
}

export const seedProducts = [
  {
    categorySlug: 'fashion',
    name: 'Handloom Cotton Shirt',
    sku: 'GV-FSN-1001',
    brand: 'Gavora Essentials',
    price: 2499,
    salePrice: 1799,
    stock: 24,
    ratingAverage: 4.5,
    ratingCount: 128,
    unitsSold: 412,
    isFeatured: true,
    createdAt: daysAgo(12),
    shortDescription: 'Breathable handloom cotton with a relaxed, unfussy cut.',
    description:
      'Woven on traditional handlooms and finished with a soft wash, this shirt is built for long Indian summers. The weave keeps air moving, and the cut is relaxed through the chest without looking oversized.',
    specifications: [
      { key: 'Material', value: '100% handloom cotton' },
      { key: 'Fit', value: 'Relaxed regular' },
      { key: 'Care', value: 'Machine wash cold, line dry in shade' },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Linen Blend Trousers',
    sku: 'GV-FSN-1003',
    brand: 'Gavora Essentials',
    price: 2899,
    salePrice: null,
    stock: 0,
    ratingAverage: 4.2,
    ratingCount: 54,
    unitsSold: 168,
    createdAt: daysAgo(48),
    shortDescription: 'Linen-cotton blend with a clean, tailored drape.',
    description:
      'Linen keeps these cool, while the cotton content stops them creasing the moment you sit down. Side-adjuster waistband, deep front pockets and a half-lined seat.',
    specifications: [
      { key: 'Material', value: '55% linen, 45% cotton' },
      { key: 'Fit', value: 'Tapered' },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Cast Iron Skillet 26cm',
    sku: 'GV-HMK-2002',
    brand: 'Ferro',
    price: 3299,
    salePrice: 2599,
    stock: 16,
    ratingAverage: 4.9,
    ratingCount: 214,
    unitsSold: 638,
    isFeatured: true,
    createdAt: daysAgo(60),
    shortDescription: 'Pre-seasoned cast iron that improves with every use.',
    description:
      'Sand-cast in a single piece with no rivets to work loose, then pre-seasoned with vegetable oil so it is ready on arrival. Holds heat long enough to sear properly.',
    specifications: [
      { key: 'Material', value: 'Cast iron, pre-seasoned' },
      { key: 'Diameter', value: '26 cm' },
      { key: 'Compatibility', value: 'Gas, induction, oven, open flame' },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Brass Table Lamp',
    sku: 'GV-HMK-2001',
    brand: 'Atelier Kosh',
    price: 5499,
    salePrice: 4299,
    stock: 9,
    ratingAverage: 4.8,
    ratingCount: 73,
    unitsSold: 184,
    isFeatured: true,
    createdAt: daysAgo(18),
    shortDescription: 'Solid brass base with a hand-stitched cotton shade.',
    description:
      'Turned from solid brass and left unlacquered, so it develops a patina over the years rather than flaking. The cotton shade throws a warm, even pool of light.',
    specifications: [
      { key: 'Material', value: 'Solid brass, cotton shade' },
      { key: 'Height', value: '42 cm' },
      { key: 'Bulb', value: 'E27, max 15W LED (not included)' },
    ],
  },
  {
    categorySlug: 'jewellery',
    name: 'Sterling Silver Hoop Earrings',
    sku: 'GV-JWL-3001',
    brand: 'Kalaa',
    price: 2199,
    salePrice: 1649,
    stock: 27,
    ratingAverage: 4.7,
    ratingCount: 156,
    unitsSold: 389,
    isFeatured: true,
    createdAt: daysAgo(15),
    shortDescription: '925 sterling silver hoops, light enough for all day.',
    description:
      'Hand-finished 925 sterling silver with a hinged catch that closes flush. At just under four grams a pair they can be worn from morning to night.',
    specifications: [
      { key: 'Material', value: '925 sterling silver' },
      { key: 'Diameter', value: '24 mm' },
      { key: 'Hallmark', value: 'BIS hallmarked' },
    ],
  },
  {
    categorySlug: 'jewellery',
    name: 'Oxidised Silver Jhumkas',
    sku: 'GV-JWL-3003',
    brand: 'Kalaa',
    price: 1799,
    salePrice: null,
    stock: 0,
    ratingAverage: 4.4,
    ratingCount: 64,
    unitsSold: 152,
    createdAt: daysAgo(55),
    shortDescription: 'Oxidised finish with fine filigree bell work.',
    description:
      'Filigree jhumkas with an oxidised finish that throws the detail into relief. Deliberately light for their size.',
    specifications: [
      { key: 'Material', value: 'Oxidised brass alloy' },
      { key: 'Drop length', value: '52 mm' },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Cold Pressed Argan Hair Oil',
    sku: 'GV-BTY-4001',
    brand: 'Sattva',
    price: 1499,
    salePrice: 1099,
    stock: 55,
    ratingAverage: 4.6,
    ratingCount: 302,
    unitsSold: 894,
    isFeatured: true,
    createdAt: daysAgo(20),
    shortDescription: 'Single-ingredient argan oil, cold pressed and unrefined.',
    description:
      'One ingredient: cold-pressed argan oil, unrefined and unscented. Packed in amber glass because argan oil degrades in light.',
    specifications: [
      { key: 'Ingredients', value: '100% Argania spinosa kernel oil' },
      { key: 'Volume', value: '100 ml' },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Vitamin C Face Serum',
    sku: 'GV-BTY-4002',
    brand: 'Sattva',
    price: 1899,
    salePrice: 1424,
    stock: 31,
    ratingAverage: 4.4,
    ratingCount: 187,
    unitsSold: 521,
    createdAt: daysAgo(14),
    shortDescription: '10% stabilised vitamin C with hyaluronic acid.',
    description:
      'A 10% stabilised vitamin C serum — high enough to be effective, low enough to suit most skin without stinging.',
    specifications: [
      { key: 'Key actives', value: '10% ethyl ascorbic acid, 1% hyaluronic acid' },
      { key: 'Volume', value: '30 ml' },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Wooden Building Blocks Set',
    sku: 'GV-TOY-5001',
    brand: 'Chotu Works',
    price: 2299,
    salePrice: 1799,
    stock: 22,
    ratingAverage: 4.8,
    ratingCount: 143,
    unitsSold: 367,
    isFeatured: true,
    createdAt: daysAgo(28),
    shortDescription: '60 solid rubberwood blocks with non-toxic finish.',
    description:
      'Sixty solid rubberwood blocks, sanded smooth and finished with food-grade non-toxic stain. No batteries, no screen, no instructions.',
    specifications: [
      { key: 'Material', value: 'Solid rubberwood' },
      { key: 'Pieces', value: '60 blocks in 8 shapes' },
      { key: 'Age', value: '3 years and above' },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Wooden Shape Puzzle Board',
    sku: 'GV-TOY-5003',
    brand: 'Little Loom',
    price: 999,
    salePrice: 749,
    stock: 47,
    ratingAverage: 4.4,
    ratingCount: 67,
    unitsSold: 178,
    createdAt: daysAgo(50),
    shortDescription: 'Chunky knobbed pieces sized for small hands.',
    description: 'Twelve chunky knobbed pieces in a solid board. Edges are fully rounded.',
    specifications: [
      { key: 'Material', value: 'Plywood with water-based paint' },
      { key: 'Pieces', value: '12' },
      { key: 'Age', value: '18 months and above' },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Waxed Canvas Weekender',
    sku: 'GV-BAG-6001',
    brand: 'Terrain Co',
    price: 6499,
    salePrice: 4999,
    stock: 8,
    ratingAverage: 4.8,
    ratingCount: 112,
    unitsSold: 287,
    isFeatured: true,
    createdAt: daysAgo(16),
    shortDescription: 'Water-resistant waxed canvas with leather trim.',
    description:
      'Waxed canvas over a leather base, with a YKK zip and box-stitched handles. Cabin-legal on most Indian carriers.',
    specifications: [
      { key: 'Material', value: '18 oz waxed canvas, full-grain leather trim' },
      { key: 'Capacity', value: '38 litres' },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Everyday Laptop Backpack',
    sku: 'GV-BAG-6002',
    brand: 'Terrain Co',
    price: 3999,
    salePrice: 3199,
    stock: 26,
    ratingAverage: 4.5,
    ratingCount: 198,
    unitsSold: 574,
    createdAt: daysAgo(26),
    shortDescription: 'Padded 15-inch sleeve with a luggage pass-through.',
    description:
      'A suspended, padded sleeve keeps a 15-inch laptop off the bottom of the bag. Water-resistant recycled shell.',
    specifications: [
      { key: 'Material', value: 'Recycled polyester, water-resistant coating' },
      { key: 'Laptop', value: 'Fits up to 15 inch' },
      { key: 'Capacity', value: '22 litres' },
    ],
  },
  {
    categorySlug: 'stationery',
    name: 'Hardbound Dotted Notebook',
    sku: 'GV-STN-7001',
    brand: 'Margin',
    price: 899,
    salePrice: 679,
    stock: 73,
    ratingAverage: 4.6,
    ratingCount: 241,
    unitsSold: 812,
    isFeatured: true,
    createdAt: daysAgo(8),
    shortDescription: '120 GSM dotted paper that will not ghost.',
    description:
      'A 120 GSM dotted notebook that takes fountain pen and fineliner without ghosting or bleeding through. Lies flat at any page.',
    specifications: [
      { key: 'Paper', value: '120 GSM, acid free' },
      { key: 'Pages', value: '192, dotted 5 mm' },
      { key: 'Size', value: 'A5, 148 x 210 mm' },
    ],
  },
  {
    categorySlug: 'stationery',
    name: 'Brass Fountain Pen',
    sku: 'GV-STN-7002',
    brand: 'Margin',
    price: 2499,
    salePrice: 1999,
    stock: 14,
    ratingAverage: 4.7,
    ratingCount: 98,
    unitsSold: 213,
    createdAt: daysAgo(21),
    shortDescription: 'Machined brass body with a fine German nib.',
    description:
      'A machined brass body that patinas with handling, fitted with a German fine steel nib. Takes standard international cartridges.',
    specifications: [
      { key: 'Body', value: 'Machined solid brass' },
      { key: 'Nib', value: 'German steel, fine' },
    ],
  },
  {
    categorySlug: 'gifts',
    name: 'Artisan Tea Gift Box',
    sku: 'GV-GFT-8001',
    brand: 'Gavora Gifting',
    price: 2499,
    salePrice: 1899,
    stock: 21,
    ratingAverage: 4.7,
    ratingCount: 132,
    unitsSold: 356,
    isFeatured: true,
    createdAt: daysAgo(10),
    shortDescription: 'Six single-estate teas in a reusable wooden box.',
    description:
      'Six single-estate teas from Darjeeling, Assam and the Nilgiris, in a reusable wooden box with a hinged lid.',
    specifications: [
      { key: 'Includes', value: '6 teas, 50 g each, with brewing card' },
      { key: 'Origins', value: 'Darjeeling, Assam, Nilgiris' },
    ],
  },
  {
    categorySlug: 'gifts',
    name: 'Festive Dry Fruit Tin',
    sku: 'GV-GFT-8004',
    brand: 'Gavora Gifting',
    price: 1799,
    salePrice: null,
    stock: 0,
    ratingAverage: 4.4,
    ratingCount: 118,
    unitsSold: 402,
    createdAt: daysAgo(5),
    shortDescription: 'Four-compartment tin of graded dry fruit.',
    description:
      'Four compartments of graded almonds, cashews, pistachios and raisins in a decorative tin that gets reused long after the contents are gone.',
    specifications: [
      { key: 'Includes', value: 'Almonds, cashews, pistachios, raisins' },
      { key: 'Net weight', value: '600 g total' },
    ],
  },
];
