/** Imported catalogue seed data. Prices/stock applied via _tmp_image_audit/apply-imported-pricing.mjs. */
function daysAgo(days) {
  return new Date(Date.now() - days * 86400000);
}

export const importedSeedProducts = [
  {
    categorySlug: 'bags',
    name: 'Geometric Quilted Flap Satchel — Mint Green',
    sku: 'GV-BAG-6101',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 28,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Geometric quilted flap satchel in mint green.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6101/01-front.svg',
        alt: 'Geometric Quilted Flap Satchel — Mint Green — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6101/02-three-quarter.svg',
        alt: 'Geometric Quilted Flap Satchel — Mint Green — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6101/03-side.svg',
        alt: 'Geometric Quilted Flap Satchel — Mint Green — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6101/04-back.svg',
        alt: 'Geometric Quilted Flap Satchel — Mint Green — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6101/05-detail.svg',
        alt: 'Geometric Quilted Flap Satchel — Mint Green — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Geometric Quilted Flap Satchel — Cream',
    sku: 'GV-BAG-6102',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 24,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Geometric quilted flap satchel in cream.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6102/01-front.svg',
        alt: 'Geometric Quilted Flap Satchel — Cream — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6102/02-three-quarter.svg',
        alt: 'Geometric Quilted Flap Satchel — Cream — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6102/03-side.svg',
        alt: 'Geometric Quilted Flap Satchel — Cream — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6102/04-back.svg',
        alt: 'Geometric Quilted Flap Satchel — Cream — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6102/05-detail.svg',
        alt: 'Geometric Quilted Flap Satchel — Cream — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Geometric Quilted Flap Satchel — Blush Pink',
    sku: 'GV-BAG-6103',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 22,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Geometric quilted flap satchel in blush pink.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6103/01-front.svg',
        alt: 'Geometric Quilted Flap Satchel — Blush Pink — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6103/02-three-quarter.svg',
        alt: 'Geometric Quilted Flap Satchel — Blush Pink — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6103/03-side.svg',
        alt: 'Geometric Quilted Flap Satchel — Blush Pink — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6103/04-back.svg',
        alt: 'Geometric Quilted Flap Satchel — Blush Pink — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6103/05-detail.svg',
        alt: 'Geometric Quilted Flap Satchel — Blush Pink — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Geometric Quilted Flap Satchel — Black',
    sku: 'GV-BAG-6104',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 31,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Geometric quilted flap satchel in black.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6104/01-front.svg',
        alt: 'Geometric Quilted Flap Satchel — Black — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6104/02-three-quarter.svg',
        alt: 'Geometric Quilted Flap Satchel — Black — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6104/03-side.svg',
        alt: 'Geometric Quilted Flap Satchel — Black — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6104/04-back.svg',
        alt: 'Geometric Quilted Flap Satchel — Black — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6104/05-detail.svg',
        alt: 'Geometric Quilted Flap Satchel — Black — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Geometric Quilted Flap Satchel — Tan',
    sku: 'GV-BAG-6105',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 19,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Geometric quilted flap satchel in tan.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6105/01-front.svg',
        alt: 'Geometric Quilted Flap Satchel — Tan — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6105/02-three-quarter.svg',
        alt: 'Geometric Quilted Flap Satchel — Tan — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6105/03-side.svg',
        alt: 'Geometric Quilted Flap Satchel — Tan — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6105/04-back.svg',
        alt: 'Geometric Quilted Flap Satchel — Tan — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6105/05-detail.svg',
        alt: 'Geometric Quilted Flap Satchel — Tan — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Interlocking Ring-Logo Satchel — Black',
    sku: 'GV-BAG-6111',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 26,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Interlocking ring-logo satchel in black.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6111/01-front.svg',
        alt: 'Interlocking Ring-Logo Satchel — Black — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6111/02-three-quarter.svg',
        alt: 'Interlocking Ring-Logo Satchel — Black — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6111/03-side.svg',
        alt: 'Interlocking Ring-Logo Satchel — Black — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6111/04-back.svg',
        alt: 'Interlocking Ring-Logo Satchel — Black — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6111/05-detail.svg',
        alt: 'Interlocking Ring-Logo Satchel — Black — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Interlocking Ring-Logo Satchel — Pink',
    sku: 'GV-BAG-6112',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 21,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Interlocking ring-logo satchel in pink.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6112/01-front.svg',
        alt: 'Interlocking Ring-Logo Satchel — Pink — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6112/02-three-quarter.svg',
        alt: 'Interlocking Ring-Logo Satchel — Pink — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6112/03-side.svg',
        alt: 'Interlocking Ring-Logo Satchel — Pink — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6112/04-back.svg',
        alt: 'Interlocking Ring-Logo Satchel — Pink — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6112/05-detail.svg',
        alt: 'Interlocking Ring-Logo Satchel — Pink — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Interlocking Ring-Logo Satchel — Beige',
    sku: 'GV-BAG-6113',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 23,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Interlocking ring-logo satchel in beige.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6113/01-front.svg',
        alt: 'Interlocking Ring-Logo Satchel — Beige — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6113/02-three-quarter.svg',
        alt: 'Interlocking Ring-Logo Satchel — Beige — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6113/03-side.svg',
        alt: 'Interlocking Ring-Logo Satchel — Beige — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6113/04-back.svg',
        alt: 'Interlocking Ring-Logo Satchel — Beige — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6113/05-detail.svg',
        alt: 'Interlocking Ring-Logo Satchel — Beige — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Interlocking Ring-Logo Satchel — Light Blue',
    sku: 'GV-BAG-6114',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 18,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Interlocking ring-logo satchel in light blue.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6114/01-front.svg',
        alt: 'Interlocking Ring-Logo Satchel — Light Blue — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6114/02-three-quarter.svg',
        alt: 'Interlocking Ring-Logo Satchel — Light Blue — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6114/03-side.svg',
        alt: 'Interlocking Ring-Logo Satchel — Light Blue — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6114/04-back.svg',
        alt: 'Interlocking Ring-Logo Satchel — Light Blue — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6114/05-detail.svg',
        alt: 'Interlocking Ring-Logo Satchel — Light Blue — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Vertical Color-Block Satchel — Beige & White',
    sku: 'GV-BAG-6121',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 27,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Vertical color-block satchel in beige and white.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6121/01-front.svg',
        alt: 'Vertical Color-Block Satchel — Beige & White — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6121/02-three-quarter.svg',
        alt: 'Vertical Color-Block Satchel — Beige & White — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6121/03-side.svg',
        alt: 'Vertical Color-Block Satchel — Beige & White — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6121/04-back.svg',
        alt: 'Vertical Color-Block Satchel — Beige & White — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6121/05-detail.svg',
        alt: 'Vertical Color-Block Satchel — Beige & White — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Vertical Color-Block Satchel — Black & White',
    sku: 'GV-BAG-6122',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 29,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Vertical color-block satchel in black and white.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6122/01-front.svg',
        alt: 'Vertical Color-Block Satchel — Black & White — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6122/02-three-quarter.svg',
        alt: 'Vertical Color-Block Satchel — Black & White — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6122/03-side.svg',
        alt: 'Vertical Color-Block Satchel — Black & White — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6122/04-back.svg',
        alt: 'Vertical Color-Block Satchel — Black & White — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6122/05-detail.svg',
        alt: 'Vertical Color-Block Satchel — Black & White — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Vertical Color-Block Satchel — Blush Pink & White',
    sku: 'GV-BAG-6123',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 20,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Vertical color-block satchel in blush pink and white.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6123/01-front.svg',
        alt: 'Vertical Color-Block Satchel — Blush Pink & White — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6123/02-three-quarter.svg',
        alt: 'Vertical Color-Block Satchel — Blush Pink & White — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6123/03-side.svg',
        alt: 'Vertical Color-Block Satchel — Blush Pink & White — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6123/04-back.svg',
        alt: 'Vertical Color-Block Satchel — Blush Pink & White — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6123/05-detail.svg',
        alt: 'Vertical Color-Block Satchel — Blush Pink & White — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Vertical Color-Block Satchel — Mauve & White',
    sku: 'GV-BAG-6124',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 17,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Vertical color-block satchel in mauve and white.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6124/01-front.svg',
        alt: 'Vertical Color-Block Satchel — Mauve & White — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6124/02-three-quarter.svg',
        alt: 'Vertical Color-Block Satchel — Mauve & White — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6124/03-side.svg',
        alt: 'Vertical Color-Block Satchel — Mauve & White — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6124/04-back.svg',
        alt: 'Vertical Color-Block Satchel — Mauve & White — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6124/05-detail.svg',
        alt: 'Vertical Color-Block Satchel — Mauve & White — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'bags',
    name: 'Vertical Color-Block Satchel — Sky Blue & White',
    sku: 'GV-BAG-6125',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 25,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Vertical color-block satchel in sky blue and white.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BAG-6125/01-front.svg',
        alt: 'Vertical Color-Block Satchel — Sky Blue & White — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BAG-6125/02-three-quarter.svg',
        alt: 'Vertical Color-Block Satchel — Sky Blue & White — three-quarter',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BAG-6125/03-side.svg',
        alt: 'Vertical Color-Block Satchel — Sky Blue & White — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-BAG-6125/04-back.svg',
        alt: 'Vertical Color-Block Satchel — Sky Blue & White — back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-BAG-6125/05-detail.svg',
        alt: 'Vertical Color-Block Satchel — Sky Blue & White — detail',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Purple Gradient Makeup Sponge Set in Clear Jar',
    sku: 'GV-BTY-4101',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 42,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Makeup sponge set in a clear jar.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4101/01-front.svg',
        alt: 'Purple Gradient Makeup Sponge Set in Clear Jar — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4101/02-top.svg',
        alt: 'Purple Gradient Makeup Sponge Set in Clear Jar — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4101/03-detail.svg',
        alt: 'Purple Gradient Makeup Sponge Set in Clear Jar — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Dusty Rose Brush & Sponge Kit with Velvet Pouch',
    sku: 'GV-BTY-4102',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 35,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Brush and sponge kit with velvet pouch.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4102/01-front.svg',
        alt: 'Dusty Rose Brush & Sponge Kit with Velvet Pouch — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4102/02-top.svg',
        alt: 'Dusty Rose Brush & Sponge Kit with Velvet Pouch — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4102/03-detail.svg',
        alt: 'Dusty Rose Brush & Sponge Kit with Velvet Pouch — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'T-Bar Facial Massager Kit with Marble Gel Eye Pads',
    sku: 'GV-BTY-4103',
    brand: 'Gavora',
    price: 649,
    salePrice: null,
    stock: 28,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'T-bar facial massager kit with gel eye pads.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4103/01-front.svg',
        alt: 'T-Bar Facial Massager Kit with Marble Gel Eye Pads — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4103/02-top.svg',
        alt: 'T-Bar Facial Massager Kit with Marble Gel Eye Pads — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4103/03-detail.svg',
        alt: 'T-Bar Facial Massager Kit with Marble Gel Eye Pads — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Neutral Deluxe Brush, Sponge & Spa Accessory Bundle',
    sku: 'GV-BTY-4104',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 22,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Brush, sponge and spa accessory bundle.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4104/01-front.svg',
        alt: 'Neutral Deluxe Brush, Sponge & Spa Accessory Bundle — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4104/02-top.svg',
        alt: 'Neutral Deluxe Brush, Sponge & Spa Accessory Bundle — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4104/03-detail.svg',
        alt: 'Neutral Deluxe Brush, Sponge & Spa Accessory Bundle — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Gold Floral Pearl Bridal Comb & Pin Set',
    sku: 'GV-BTY-4105',
    brand: 'Gavora',
    price: 599,
    salePrice: null,
    stock: 30,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Floral pearl bridal comb and pin set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4105/01-front.svg',
        alt: 'Gold Floral Pearl Bridal Comb & Pin Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4105/02-top.svg',
        alt: 'Gold Floral Pearl Bridal Comb & Pin Set — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4105/03-detail.svg',
        alt: 'Gold Floral Pearl Bridal Comb & Pin Set — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Triple Floral Pearl-Drape Brooch — Emerald',
    sku: 'GV-BTY-4106',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 33,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Triple floral pearl-drape brooch in emerald.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4106/01-front.svg',
        alt: 'Triple Floral Pearl-Drape Brooch — Emerald — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4106/02-top.svg',
        alt: 'Triple Floral Pearl-Drape Brooch — Emerald — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4106/03-detail.svg',
        alt: 'Triple Floral Pearl-Drape Brooch — Emerald — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Triple Floral Pearl-Drape Brooch — Burgundy',
    sku: 'GV-BTY-4107',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 31,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Triple floral pearl-drape brooch in burgundy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4107/01-front.svg',
        alt: 'Triple Floral Pearl-Drape Brooch — Burgundy — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4107/02-top.svg',
        alt: 'Triple Floral Pearl-Drape Brooch — Burgundy — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4107/03-detail.svg',
        alt: 'Triple Floral Pearl-Drape Brooch — Burgundy — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Dual-Flower Gemstone Mini Claw Clip Set',
    sku: 'GV-BTY-4108',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 40,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Dual-flower gemstone mini claw clip set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4108/01-front.svg',
        alt: 'Dual-Flower Gemstone Mini Claw Clip Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4108/02-top.svg',
        alt: 'Dual-Flower Gemstone Mini Claw Clip Set — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4108/03-detail.svg',
        alt: 'Dual-Flower Gemstone Mini Claw Clip Set — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'White Handle Professional Makeup Brush Set',
    sku: 'GV-BTY-4109',
    brand: 'Gavora',
    price: 599,
    salePrice: null,
    stock: 36,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'White-handle makeup brush set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4109/01-front.svg',
        alt: 'White Handle Professional Makeup Brush Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4109/02-top.svg',
        alt: 'White Handle Professional Makeup Brush Set — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4109/03-detail.svg',
        alt: 'White Handle Professional Makeup Brush Set — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: '5-in-1 Hot Air Hair Styler Kit — Sky Blue',
    sku: 'GV-BTY-4110',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 16,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: '5-in-1 hot air hair styler kit.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4110/01-front.svg',
        alt: '5-in-1 Hot Air Hair Styler Kit — Sky Blue — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4110/02-top.svg',
        alt: '5-in-1 Hot Air Hair Styler Kit — Sky Blue — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4110/03-detail.svg',
        alt: '5-in-1 Hot Air Hair Styler Kit — Sky Blue — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Angel-Wing Pearl Tassel Hair Clip',
    sku: 'GV-BTY-4111',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 38,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Angel-wing pearl tassel hair clip.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4111/01-front.svg',
        alt: 'Angel-Wing Pearl Tassel Hair Clip — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4111/02-top.svg',
        alt: 'Angel-Wing Pearl Tassel Hair Clip — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-BTY-4111/03-detail.svg',
        alt: 'Angel-Wing Pearl Tassel Hair Clip — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Lavender Makeup Brush Set with Case',
    sku: 'GV-BTY-4112',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 34,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Lavender makeup brush set with case.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4112/01-front.svg',
        alt: 'Lavender Makeup Brush Set with Case — front',
        isPrimary: true,
        position: 0,
      },
    ],
  },
  {
    categorySlug: 'beauty',
    name: 'Natural Wood Oval Paddle Hairbrush',
    sku: 'GV-BTY-4113',
    brand: 'Gavora',
    price: 499,
    salePrice: null,
    stock: 41,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Natural wood oval paddle hairbrush.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-BTY-4113/01-front.svg',
        alt: 'Natural Wood Oval Paddle Hairbrush — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-BTY-4113/02-back.svg',
        alt: 'Natural Wood Oval Paddle Hairbrush — back',
        isPrimary: false,
        position: 1,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Maroon Printed Kurta Set with Patterned Dupatta',
    sku: 'GV-FSN-1101',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 18,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Printed kurta set with patterned dupatta.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1101/01-front.svg',
        alt: 'Maroon Printed Kurta Set with Patterned Dupatta — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1101/02-side.svg',
        alt: 'Maroon Printed Kurta Set with Patterned Dupatta — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1101/03-back.svg',
        alt: 'Maroon Printed Kurta Set with Patterned Dupatta — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1101/04-angle.svg',
        alt: 'Maroon Printed Kurta Set with Patterned Dupatta — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Pink & White Abstract Print Long-Sleeve Blouse',
    sku: 'GV-FSN-1102',
    brand: 'Gavora',
    price: 599,
    salePrice: null,
    stock: 27,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Abstract print long-sleeve blouse.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1102/01-front.svg',
        alt: 'Pink & White Abstract Print Long-Sleeve Blouse — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1102/02-side.svg',
        alt: 'Pink & White Abstract Print Long-Sleeve Blouse — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1102/03-back.svg',
        alt: 'Pink & White Abstract Print Long-Sleeve Blouse — back',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Dark Green Pleated Midi Dress',
    sku: 'GV-FSN-1103',
    brand: 'Gavora',
    price: 649,
    salePrice: null,
    stock: 23,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Pleated midi dress in dark green.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1103/01-front.svg',
        alt: 'Dark Green Pleated Midi Dress — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1103/02-side.svg',
        alt: 'Dark Green Pleated Midi Dress — side',
        isPrimary: false,
        position: 1,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Black Top & Grey Wide-Leg Trouser Set',
    sku: 'GV-FSN-1104',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 20,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Black top and grey wide-leg trouser set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1104/01-front.svg',
        alt: 'Black Top & Grey Wide-Leg Trouser Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1104/02-side.svg',
        alt: 'Black Top & Grey Wide-Leg Trouser Set — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1104/03-back.svg',
        alt: 'Black Top & Grey Wide-Leg Trouser Set — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1104/04-angle.svg',
        alt: 'Black Top & Grey Wide-Leg Trouser Set — angle',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-FSN-1104/05-lifestyle.svg',
        alt: 'Black Top & Grey Wide-Leg Trouser Set — lifestyle',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Beige Long-Sleeve Co-ord Set',
    sku: 'GV-FSN-1105',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 19,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Beige long-sleeve co-ord set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1105/01-front.svg',
        alt: 'Beige Long-Sleeve Co-ord Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1105/02-side.svg',
        alt: 'Beige Long-Sleeve Co-ord Set — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1105/03-back.svg',
        alt: 'Beige Long-Sleeve Co-ord Set — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1105/04-angle.svg',
        alt: 'Beige Long-Sleeve Co-ord Set — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Maroon Velvet Spaghetti-Strap Midi Dress',
    sku: 'GV-FSN-1106',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 21,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Velvet spaghetti-strap midi dress.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1106/01-front.svg',
        alt: 'Maroon Velvet Spaghetti-Strap Midi Dress — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1106/02-side.svg',
        alt: 'Maroon Velvet Spaghetti-Strap Midi Dress — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1106/03-back.svg',
        alt: 'Maroon Velvet Spaghetti-Strap Midi Dress — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1106/04-angle.svg',
        alt: 'Maroon Velvet Spaghetti-Strap Midi Dress — angle',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-FSN-1106/05-lifestyle.svg',
        alt: 'Maroon Velvet Spaghetti-Strap Midi Dress — lifestyle',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Blue Color-Block Zip Jacket with Wide-Leg Jeans',
    sku: 'GV-FSN-1107',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 15,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Color-block zip jacket with wide-leg jeans.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1107/01-front.svg',
        alt: 'Blue Color-Block Zip Jacket with Wide-Leg Jeans — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1107/02-side.svg',
        alt: 'Blue Color-Block Zip Jacket with Wide-Leg Jeans — side',
        isPrimary: false,
        position: 1,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Vertical Stripe Sleeveless Vest Suit',
    sku: 'GV-FSN-1108',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 14,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Vertical stripe sleeveless vest suit.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1108/01-front.svg',
        alt: 'Vertical Stripe Sleeveless Vest Suit — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1108/02-side.svg',
        alt: 'Vertical Stripe Sleeveless Vest Suit — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1108/03-back.svg',
        alt: 'Vertical Stripe Sleeveless Vest Suit — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1108/04-angle.svg',
        alt: 'Vertical Stripe Sleeveless Vest Suit — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Black Mock-Neck Crop Top with Flare Jeans',
    sku: 'GV-FSN-1109',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 24,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Mock-neck crop top with flare jeans.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1109/01-front.svg',
        alt: 'Black Mock-Neck Crop Top with Flare Jeans — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1109/02-side.svg',
        alt: 'Black Mock-Neck Crop Top with Flare Jeans — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1109/03-back.svg',
        alt: 'Black Mock-Neck Crop Top with Flare Jeans — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1109/04-angle.svg',
        alt: 'Black Mock-Neck Crop Top with Flare Jeans — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Navy Short-Sleeve Midi Dress',
    sku: 'GV-FSN-1110',
    brand: 'Gavora',
    price: 649,
    salePrice: null,
    stock: 26,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Navy short-sleeve midi dress.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1110/01-front.svg',
        alt: 'Navy Short-Sleeve Midi Dress — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1110/02-side.svg',
        alt: 'Navy Short-Sleeve Midi Dress — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1110/03-back.svg',
        alt: 'Navy Short-Sleeve Midi Dress — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1110/04-angle.svg',
        alt: 'Navy Short-Sleeve Midi Dress — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Green Floral Print Midi Dress',
    sku: 'GV-FSN-1111',
    brand: 'Gavora',
    price: 649,
    salePrice: null,
    stock: 25,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Floral print midi dress in green.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1111/01-front.svg',
        alt: 'Green Floral Print Midi Dress — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1111/02-side.svg',
        alt: 'Green Floral Print Midi Dress — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1111/03-back.svg',
        alt: 'Green Floral Print Midi Dress — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1111/04-angle.svg',
        alt: 'Green Floral Print Midi Dress — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'White Tailored Blazer & Trouser Suit',
    sku: 'GV-FSN-1112',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 12,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'White tailored blazer and trouser suit.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1112/01-front.svg',
        alt: 'White Tailored Blazer & Trouser Suit — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1112/02-side.svg',
        alt: 'White Tailored Blazer & Trouser Suit — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1112/03-back.svg',
        alt: 'White Tailored Blazer & Trouser Suit — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1112/04-angle.svg',
        alt: 'White Tailored Blazer & Trouser Suit — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'fashion',
    name: 'Navy Blue Gold-Zari Border Saree',
    sku: 'GV-FSN-1113',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 16,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Navy blue saree with gold-zari border.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-FSN-1113/01-front.svg',
        alt: 'Navy Blue Gold-Zari Border Saree — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-FSN-1113/02-side.svg',
        alt: 'Navy Blue Gold-Zari Border Saree — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-FSN-1113/03-back.svg',
        alt: 'Navy Blue Gold-Zari Border Saree — back',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-FSN-1113/04-angle.svg',
        alt: 'Navy Blue Gold-Zari Border Saree — angle',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Cream Ribbed Ceramic Dinnerware Set',
    sku: 'GV-HMK-2101',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 18,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Cream ribbed ceramic dinnerware set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2101/01-front.svg',
        alt: 'Cream Ribbed Ceramic Dinnerware Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2101/02-top.svg',
        alt: 'Cream Ribbed Ceramic Dinnerware Set — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2101/03-detail.svg',
        alt: 'Cream Ribbed Ceramic Dinnerware Set — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Blue Spin Mop and Bucket System',
    sku: 'GV-HMK-2102',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 22,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Spin mop and bucket system.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2102/01-front.svg',
        alt: 'Blue Spin Mop and Bucket System — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2102/02-top.svg',
        alt: 'Blue Spin Mop and Bucket System — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2102/03-detail.svg',
        alt: 'Blue Spin Mop and Bucket System — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Grey Woven-Pattern Laundry Basket',
    sku: 'GV-HMK-2103',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 30,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Woven-pattern laundry basket.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2103/01-front.svg',
        alt: 'Grey Woven-Pattern Laundry Basket — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2103/02-top.svg',
        alt: 'Grey Woven-Pattern Laundry Basket — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2103/03-detail.svg',
        alt: 'Grey Woven-Pattern Laundry Basket — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Black Two-Tier Spice Rack with Glass Jars',
    sku: 'GV-HMK-2104',
    brand: 'Gavora',
    price: 599,
    salePrice: null,
    stock: 27,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Two-tier spice rack with glass jars.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2104/01-front.svg',
        alt: 'Black Two-Tier Spice Rack with Glass Jars — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2104/02-top.svg',
        alt: 'Black Two-Tier Spice Rack with Glass Jars — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2104/03-detail.svg',
        alt: 'Black Two-Tier Spice Rack with Glass Jars — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Black Digital Touchscreen Air Fryer',
    sku: 'GV-HMK-2105',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 14,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Digital touchscreen air fryer.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2105/01-front.svg',
        alt: 'Black Digital Touchscreen Air Fryer — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2105/02-top.svg',
        alt: 'Black Digital Touchscreen Air Fryer — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2105/03-detail.svg',
        alt: 'Black Digital Touchscreen Air Fryer — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'White Multi-Function Food Processor & Blender',
    sku: 'GV-HMK-2106',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 13,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Multi-function food processor and blender.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2106/01-front.svg',
        alt: 'White Multi-Function Food Processor & Blender — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2106/02-side.svg',
        alt: 'White Multi-Function Food Processor & Blender — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2106/03-side-left.svg',
        alt: 'White Multi-Function Food Processor & Blender — side-left',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-HMK-2106/04-top.svg',
        alt: 'White Multi-Function Food Processor & Blender — top',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-HMK-2106/05-detail.svg',
        alt: 'White Multi-Function Food Processor & Blender — detail',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-HMK-2106/06-components.svg',
        alt: 'White Multi-Function Food Processor & Blender — components',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Gold-Rim Glass, Bowl & Gold Cutlery Dining Set',
    sku: 'GV-HMK-2107',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 17,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Gold-rim glass, bowl and cutlery dining set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2107/01-front.svg',
        alt: 'Gold-Rim Glass, Bowl & Gold Cutlery Dining Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2107/02-detail.svg',
        alt: 'Gold-Rim Glass, Bowl & Gold Cutlery Dining Set — detail',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2107/03-angle.svg',
        alt: 'Gold-Rim Glass, Bowl & Gold Cutlery Dining Set — angle',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Stainless Steel Electric Kettle',
    sku: 'GV-HMK-2108',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 29,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Stainless steel electric kettle.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2108/01-front.svg',
        alt: 'Stainless Steel Electric Kettle — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2108/02-top.svg',
        alt: 'Stainless Steel Electric Kettle — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2108/03-detail.svg',
        alt: 'Stainless Steel Electric Kettle — detail',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Classic Aluminum Moka Pot Espresso Maker',
    sku: 'GV-HMK-2109',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 32,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Classic aluminum moka pot espresso maker.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2109/01-front.svg',
        alt: 'Classic Aluminum Moka Pot Espresso Maker — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2109/02-angle.svg',
        alt: 'Classic Aluminum Moka Pot Espresso Maker — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2109/03-detail.svg',
        alt: 'Classic Aluminum Moka Pot Espresso Maker — detail',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-HMK-2109/04-detail-spout.svg',
        alt: 'Classic Aluminum Moka Pot Espresso Maker — detail-spout',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Wood-Handle Cooking Utensil Set',
    sku: 'GV-HMK-2110',
    brand: 'Gavora',
    price: 499,
    salePrice: null,
    stock: 36,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Wood-handle cooking utensil set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2110/01-front.svg',
        alt: 'Wood-Handle Cooking Utensil Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-HMK-2110/02-spatula.svg',
        alt: 'Wood-Handle Cooking Utensil Set — spatula',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-HMK-2110/03-whisk.svg',
        alt: 'Wood-Handle Cooking Utensil Set — whisk',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-HMK-2110/04-spiral-whisk.svg',
        alt: 'Wood-Handle Cooking Utensil Set — spiral-whisk',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-HMK-2110/05-slotted-spatula.svg',
        alt: 'Wood-Handle Cooking Utensil Set — slotted-spatula',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'home-kitchen',
    name: 'Non-Stick Electric Hot Pot with Glass Lid',
    sku: 'GV-HMK-2111',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 20,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Non-stick electric hot pot with glass lid.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-HMK-2111/01-front.svg',
        alt: 'Non-Stick Electric Hot Pot with Glass Lid — front',
        isPrimary: true,
        position: 0,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Yellow Transforming Robot Sports Car',
    sku: 'GV-TOY-5101',
    brand: 'Gavora',
    price: 649,
    salePrice: null,
    stock: 28,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Transforming robot sports car toy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5101/01-front.svg',
        alt: 'Yellow Transforming Robot Sports Car — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5101/02-robot-front.svg',
        alt: 'Yellow Transforming Robot Sports Car — robot-front',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5101/03-robot-angle.svg',
        alt: 'Yellow Transforming Robot Sports Car — robot-angle',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5101/04-robot-back.svg',
        alt: 'Yellow Transforming Robot Sports Car — robot-back',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5101/05-robot-side.svg',
        alt: 'Yellow Transforming Robot Sports Car — robot-side',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5101/06-car-rear.svg',
        alt: 'Yellow Transforming Robot Sports Car — car-rear',
        isPrimary: false,
        position: 5,
      },
      {
        url: '/products/GV-TOY-5101/07-car-top.svg',
        alt: 'Yellow Transforming Robot Sports Car — car-top',
        isPrimary: false,
        position: 6,
      },
      {
        url: '/products/GV-TOY-5101/08-car-bottom.svg',
        alt: 'Yellow Transforming Robot Sports Car — car-bottom',
        isPrimary: false,
        position: 7,
      },
      {
        url: '/products/GV-TOY-5101/09-kit.svg',
        alt: 'Yellow Transforming Robot Sports Car — kit',
        isPrimary: false,
        position: 8,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Red/Black Transforming Robot Racing Car',
    sku: 'GV-TOY-5102',
    brand: 'Gavora',
    price: 699,
    salePrice: null,
    stock: 24,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Transforming robot racing car toy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5102/01-front.svg',
        alt: 'Red/Black Transforming Robot Racing Car — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5102/02-angle.svg',
        alt: 'Red/Black Transforming Robot Racing Car — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5102/03-side.svg',
        alt: 'Red/Black Transforming Robot Racing Car — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5102/04-rear.svg',
        alt: 'Red/Black Transforming Robot Racing Car — rear',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5102/05-robot-front.svg',
        alt: 'Red/Black Transforming Robot Racing Car — robot-front',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5102/06-robot-angle.svg',
        alt: 'Red/Black Transforming Robot Racing Car — robot-angle',
        isPrimary: false,
        position: 5,
      },
      {
        url: '/products/GV-TOY-5102/07-car-top.svg',
        alt: 'Red/Black Transforming Robot Racing Car — car-top',
        isPrimary: false,
        position: 6,
      },
      {
        url: '/products/GV-TOY-5102/08-car-bottom.svg',
        alt: 'Red/Black Transforming Robot Racing Car — car-bottom',
        isPrimary: false,
        position: 7,
      },
      {
        url: '/products/GV-TOY-5102/09-kit.svg',
        alt: 'Red/Black Transforming Robot Racing Car — kit',
        isPrimary: false,
        position: 8,
      },
      {
        url: '/products/GV-TOY-5102/10-lifestyle.svg',
        alt: 'Red/Black Transforming Robot Racing Car — lifestyle',
        isPrimary: false,
        position: 9,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Minion Prisoner Outfit Character Figure',
    sku: 'GV-TOY-5103',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 40,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Character figure in prisoner outfit.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5103/01-front.svg',
        alt: 'Minion Prisoner Outfit Character Figure — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5103/02-side.svg',
        alt: 'Minion Prisoner Outfit Character Figure — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5103/03-top.svg',
        alt: 'Minion Prisoner Outfit Character Figure — top',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'White A380 Remote-Control Passenger Plane',
    sku: 'GV-TOY-5104',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 15,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Remote-control passenger plane toy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5104/01-front.svg',
        alt: 'White A380 Remote-Control Passenger Plane — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5104/02-top.svg',
        alt: 'White A380 Remote-Control Passenger Plane — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5104/03-bottom.svg',
        alt: 'White A380 Remote-Control Passenger Plane — bottom',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5104/04-rear.svg',
        alt: 'White A380 Remote-Control Passenger Plane — rear',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5104/05-side.svg',
        alt: 'White A380 Remote-Control Passenger Plane — side',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5104/06-kit.svg',
        alt: 'White A380 Remote-Control Passenger Plane — kit',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Grey Stealth Fighter Jet RC Toy',
    sku: 'GV-TOY-5105',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 18,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Stealth fighter jet remote-control toy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5105/01-front.svg',
        alt: 'Grey Stealth Fighter Jet RC Toy — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5105/02-top.svg',
        alt: 'Grey Stealth Fighter Jet RC Toy — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5105/03-bottom.svg',
        alt: 'Grey Stealth Fighter Jet RC Toy — bottom',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5105/04-rear.svg',
        alt: 'Grey Stealth Fighter Jet RC Toy — rear',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5105/05-side.svg',
        alt: 'Grey Stealth Fighter Jet RC Toy — side',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5105/06-angle.svg',
        alt: 'Grey Stealth Fighter Jet RC Toy — angle',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Yellow Rudman RC Off-Road Jeep',
    sku: 'GV-TOY-5106',
    brand: 'Gavora',
    price: 749,
    salePrice: null,
    stock: 19,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Remote-control off-road jeep toy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5106/01-front.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5106/02-top.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5106/03-bottom.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — bottom',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5106/04-rear.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — rear',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5106/05-side.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — side',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5106/06-side-right.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — side-right',
        isPrimary: false,
        position: 5,
      },
      {
        url: '/products/GV-TOY-5106/07-angle.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — angle',
        isPrimary: false,
        position: 6,
      },
      {
        url: '/products/GV-TOY-5106/08-kit.svg',
        alt: 'Yellow Rudman RC Off-Road Jeep — kit',
        isPrimary: false,
        position: 7,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Yellow YIGONG Toy Excavator',
    sku: 'GV-TOY-5107',
    brand: 'Gavora',
    price: 599,
    salePrice: null,
    stock: 26,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Toy excavator.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5107/01-front.svg',
        alt: 'Yellow YIGONG Toy Excavator — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5107/02-top.svg',
        alt: 'Yellow YIGONG Toy Excavator — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5107/03-bottom.svg',
        alt: 'Yellow YIGONG Toy Excavator — bottom',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5107/04-rear.svg',
        alt: 'Yellow YIGONG Toy Excavator — rear',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5107/05-side.svg',
        alt: 'Yellow YIGONG Toy Excavator — side',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5107/06-side-right.svg',
        alt: 'Yellow YIGONG Toy Excavator — side-right',
        isPrimary: false,
        position: 5,
      },
      {
        url: '/products/GV-TOY-5107/07-angle.svg',
        alt: 'Yellow YIGONG Toy Excavator — angle',
        isPrimary: false,
        position: 6,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Grey Model D90 Expedition SUV Toy',
    sku: 'GV-TOY-5108',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 30,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Model expedition SUV toy.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5108/01-front.svg',
        alt: 'Grey Model D90 Expedition SUV Toy — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5108/02-top.svg',
        alt: 'Grey Model D90 Expedition SUV Toy — top',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5108/03-rear.svg',
        alt: 'Grey Model D90 Expedition SUV Toy — rear',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5108/04-side.svg',
        alt: 'Grey Model D90 Expedition SUV Toy — side',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5108/05-side-right.svg',
        alt: 'Grey Model D90 Expedition SUV Toy — side-right',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5108/06-angle.svg',
        alt: 'Grey Model D90 Expedition SUV Toy — angle',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Black RC Off-Road Jeep with Remote',
    sku: 'GV-TOY-5109',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 16,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Remote-control off-road jeep with remote.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5109/01-front.svg',
        alt: 'Black RC Off-Road Jeep with Remote — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5109/02-angle.svg',
        alt: 'Black RC Off-Road Jeep with Remote — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5109/03-side.svg',
        alt: 'Black RC Off-Road Jeep with Remote — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5109/04-top.svg',
        alt: 'Black RC Off-Road Jeep with Remote — top',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5109/05-rear.svg',
        alt: 'Black RC Off-Road Jeep with Remote — rear',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5109/06-kit.svg',
        alt: 'Black RC Off-Road Jeep with Remote — kit',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Blue & Yellow Propeller Toy Airplane',
    sku: 'GV-TOY-5110',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 38,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Propeller toy airplane.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5110/01-front.svg',
        alt: 'Blue & Yellow Propeller Toy Airplane — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5110/02-angle.svg',
        alt: 'Blue & Yellow Propeller Toy Airplane — angle',
        isPrimary: false,
        position: 1,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Kids Racket Set with Balls',
    sku: 'GV-TOY-5111',
    brand: 'Gavora',
    price: 499,
    salePrice: null,
    stock: 35,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Kids racket set with balls.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5111/01-front.svg',
        alt: 'Kids Racket Set with Balls — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5111/02-angle.svg',
        alt: 'Kids Racket Set with Balls — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5111/03-rear.svg',
        alt: 'Kids Racket Set with Balls — rear',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5111/04-kit.svg',
        alt: 'Kids Racket Set with Balls — kit',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Ball Catcher & Launcher Cone Set',
    sku: 'GV-TOY-5112',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 42,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Ball catcher and launcher cone set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5112/01-front.svg',
        alt: 'Ball Catcher & Launcher Cone Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5112/02-side.svg',
        alt: 'Ball Catcher & Launcher Cone Set — side',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5112/03-kit.svg',
        alt: 'Ball Catcher & Launcher Cone Set — kit',
        isPrimary: false,
        position: 2,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Kids Archery Set with Target',
    sku: 'GV-TOY-5113',
    brand: 'Gavora',
    price: 549,
    salePrice: null,
    stock: 29,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Kids archery set with target.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5113/01-front.svg',
        alt: 'Kids Archery Set with Target — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5113/02-angle.svg',
        alt: 'Kids Archery Set with Target — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5113/03-detail.svg',
        alt: 'Kids Archery Set with Target — detail',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5113/04-kit.svg',
        alt: 'Kids Archery Set with Target — kit',
        isPrimary: false,
        position: 3,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Cute Buddies Yellow/Blue Toddler Ride-On Car',
    sku: 'GV-TOY-5114',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 12,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Toddler ride-on car.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5114/01-front.svg',
        alt: 'Cute Buddies Yellow/Blue Toddler Ride-On Car — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5114/02-angle.svg',
        alt: 'Cute Buddies Yellow/Blue Toddler Ride-On Car — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5114/03-side.svg',
        alt: 'Cute Buddies Yellow/Blue Toddler Ride-On Car — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5114/04-rear.svg',
        alt: 'Cute Buddies Yellow/Blue Toddler Ride-On Car — rear',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5114/05-top.svg',
        alt: 'Cute Buddies Yellow/Blue Toddler Ride-On Car — top',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5114/06-kit.svg',
        alt: 'Cute Buddies Yellow/Blue Toddler Ride-On Car — kit',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Kids Cricket Bat, Ball & Stumps Set',
    sku: 'GV-TOY-5115',
    brand: 'Gavora',
    price: 599,
    salePrice: null,
    stock: 27,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Kids cricket bat, ball and stumps set.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5115/01-front.svg',
        alt: 'Kids Cricket Bat, Ball & Stumps Set — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5115/02-angle.svg',
        alt: 'Kids Cricket Bat, Ball & Stumps Set — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5115/03-top.svg',
        alt: 'Kids Cricket Bat, Ball & Stumps Set — top',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5115/04-detail.svg',
        alt: 'Kids Cricket Bat, Ball & Stumps Set — detail',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5115/05-kit.svg',
        alt: 'Kids Cricket Bat, Ball & Stumps Set — kit',
        isPrimary: false,
        position: 4,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Orange Drum-Magazine Foam Dart Blaster',
    sku: 'GV-TOY-5116',
    brand: 'Gavora',
    price: 649,
    salePrice: null,
    stock: 23,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Foam dart blaster with drum magazine.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5116/01-front.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5116/02-rear.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — rear',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5116/03-side.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5116/04-side-right.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — side-right',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5116/05-top.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — top',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5116/06-angle.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — angle',
        isPrimary: false,
        position: 5,
      },
      {
        url: '/products/GV-TOY-5116/07-kit.svg',
        alt: 'Orange Drum-Magazine Foam Dart Blaster — kit',
        isPrimary: false,
        position: 6,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Blue Kids Electric Ride-On Jeep',
    sku: 'GV-TOY-5117',
    brand: 'Gavora',
    price: 799,
    salePrice: null,
    stock: 11,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Kids electric ride-on jeep.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5117/01-front.svg',
        alt: 'Blue Kids Electric Ride-On Jeep — front',
        isPrimary: true,
        position: 0,
      },
      {
        url: '/products/GV-TOY-5117/02-angle.svg',
        alt: 'Blue Kids Electric Ride-On Jeep — angle',
        isPrimary: false,
        position: 1,
      },
      {
        url: '/products/GV-TOY-5117/03-side.svg',
        alt: 'Blue Kids Electric Ride-On Jeep — side',
        isPrimary: false,
        position: 2,
      },
      {
        url: '/products/GV-TOY-5117/04-top.svg',
        alt: 'Blue Kids Electric Ride-On Jeep — top',
        isPrimary: false,
        position: 3,
      },
      {
        url: '/products/GV-TOY-5117/05-rear.svg',
        alt: 'Blue Kids Electric Ride-On Jeep — rear',
        isPrimary: false,
        position: 4,
      },
      {
        url: '/products/GV-TOY-5117/06-bottom.svg',
        alt: 'Blue Kids Electric Ride-On Jeep — bottom',
        isPrimary: false,
        position: 5,
      },
    ],
  },
  {
    categorySlug: 'toys',
    name: 'Rainbow Soft Soccer Ball',
    sku: 'GV-TOY-5118',
    brand: 'Gavora',
    price: 449,
    salePrice: null,
    stock: 45,
    ratingAverage: 0,
    ratingCount: 0,
    unitsSold: 0,
    isFeatured: false,
    createdAt: daysAgo(1),
    shortDescription: 'Soft soccer ball.',
    description: 'NEEDS DATA — imported from existing project product assets. Pricing, stock and merchandising copy are pending review.',
    specifications: [],
    images: [
      {
        url: '/products/GV-TOY-5118/01-front.svg',
        alt: 'Rainbow Soft Soccer Ball — front',
        isPrimary: true,
        position: 0,
      },
    ],
  },
];

export const importedCatalogueMeta = {
  "generatedAt": "2026-09-17T18:21:32.564Z",
  "productCount": 69,
  "copied": 291,
  "missing": 0
};
